version: '3'


services:
  postgis:
    build:
      context: ./postgis
    volumes:
      - pg_analytical:/var/lib/postgresql
      - gisdata:/gisdata
      - ./backups:/opt/backups
      - "./postgis/loader-scripts:/usr/local/src"
    environment:
      - POSTGRES_USER=${POSTGRES_GIS_USER}
      - POSTGRES_PASS=${POSTGRES_GIS_USER_PASSWORD}
      - POSTGRES_GIS_DATABASE=${POSTGRES_GIS_DATABASE}
      - POSTGRES_GIS_USER=${POSTGRES_GIS_USER}
      - POSTGRES_GIS_USER_PASSWORD=${POSTGRES_GIS_USER_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,ogr_fdw,fuzzystrmatch,postgis_tiger_geocoder,address_standardizer
    ports:
      - 5433:5432
    restart: on-failure
    healthcheck:
      test: 'exit 0'



volumes:
  pg_analytical:
  gisdata:
