#! /bin/bash

set -e


psql v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
  CREATE USER $POSTGRES_GIS_USER WITH PASSWORD '$POSTGRES_GIS_USER_PASSWORD';
  CREATE DATABASE $POSTGRES_GIS_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_GIS_DATABASE to $POSTGRES_GIS_USER;
EOSQL



